/**
 * Pinned snapshot of the procedural volumetric fog (pre video-fog trial).
 *
 * Restoring: `__stage.setVolumetricParams({ ...PINNED_FOG_PARAMS })` then
 * FINALIZE, or copy into fogConfig.js schema defaults; set
 * `STAGE_FOG_MODE = "volumetric"`. Live path is volumetric by default —
 * video sheets stay behind `debugFog('video')` only (flat sheets band at
 * grazing forever; do not feather them into the default).
 *
 * Do not edit this file to "tune" fog — it is a rollback pin only.
 * Pinned: 16 September 2026 (Manual 1 + look pass).
 */

/** Frozen Manual 1 look (banding-proof continuous density — no sheet layers). */
export const PINNED_FOG_PARAMS = Object.freeze({
  halfRes: true,
  fogMinY: -0.1,
  fogFloorFadeRangeY: 1.35,
  fogMaxY: 12.8,
  fogFadeOutRangeY: 1.2,
  fogFadeOutPow: 1.2,
  heightFogFactor: 0.54,
  heightFogStartY: -1,
  heightFogEndY: 0,
  heightFogExpK: 0.55,
  heightFogHazeStartY: 0.12,
  // Manual 1 used 0.5 — TOO TIGHT at grazing (§20.9b). Live fogConfig is 2.0.
  // Pin keeps historical Manual 1; do not FINALIZE this narrow range into live.
  heightFogHazeRangeY: 0.5,
  heightFogHazeFloor: 0.1,
  fogDensityMultiplier: 0.4,
  baseRaymarchStepCount: 64,
  baseMaxRayLength: 32,
  noiseBias: 0.22,
  noisePow: 3.15,
  globalScale: 1.45,
  noiseMovementX: 0.06,
  noiseMovementY: 0.06,
  noiseSpeed: 7.95,
  outputDither: 0.02,
  outputPixelSize: 0,
  digitalNoiseCell: 0.14,
  digitalNoiseAmount: 0,
  subjectWrapRadius: 0,
  subjectWrapBoost: 0,
  // Never restore a density-multiplier maxY — that reintroduced grazing bands.
  subjectWrapMaxY: 12,
  falloffNoiseWarp: 1.85,
  falloffCeilingJitter: 0.95,
  // Manual 1 12→18 intersects Bust floor hits (~10–16 m) → grazing shelves.
  // Live fogConfig is 24→32; do not FINALIZE this window into live.
  fogDistFadeStart: 12,
  fogDistFadeEnd: 18,
  fogNearFadeStart: 0.35,
  fogNearFadeEnd: 3.5,
  noiseYSlice: 0,
  noiseYScroll: -0.019
});

/**
 * Stage constants that shaped the pinned look (not in fogConfig.js).
 */
export const PINNED_STAGE_FOG_CONTEXT = Object.freeze({
  VIGNETTE_FOG_RADIUS: 8.0,
  VIGNETTE_FOG_FEATHER: 2.2,
  VIGNETTE_FOG_LIGHT_DISTANCE: 6.5,
  VIGNETTE_FOG_LIGHT_DECAY: 1.85,
  NEON_LIGHT_DISTANCE: 2.75,
  NEON_LIGHT_DECAY: 3.5,
  AMBIENT_INTENSITY: 0.008,
  HEMI_INTENSITY: 0.004,
  /** VolumetricFogPass march uniform (hardcoded in pass, not fogConfig). */
  uAmbient: 0.08,
  FOG_HEAVY_FADE_IN_MS: 400,
  FOG_IN_SCATTER_FILL_CAP: 0.88,
  FOG_IN_SCATTER_CORE_KEEP: 0.22
});

/** Convenience bundle for probes / README. */
export const PINNED_VOLUMETRIC_FOG = Object.freeze({
  pinnedAt: "2026-09-16",
  reason: "Pre-trial pin before alpha VideoTexture fog planes",
  FOG_PARAMS: PINNED_FOG_PARAMS,
  STAGE: PINNED_STAGE_FOG_CONTEXT
});
